table fact_ratios
	lineageTag: c230edb9-c1a0-4a87-bb69-dde422115823

	column ROW_ID
		dataType: int64
		formatString: 0
		lineageTag: 6ae3a01a-b510-42b3-9433-c675095a2fff
		summarizeBy: count
		sourceColumn: ROW_ID

		annotation SummarizationSetBy = Automatic

	column BANK_ID
		dataType: int64
		formatString: 0
		lineageTag: 3989895d-9c59-4fa0-b3cc-a1bb4dedfb1f
		summarizeBy: none
		sourceColumn: BANK_ID

		annotation SummarizationSetBy = Automatic

	column COUNTRY_CODE
		dataType: string
		lineageTag: 5d79d3df-e9d4-403a-b200-e426afa8e223
		summarizeBy: none
		sourceColumn: COUNTRY_CODE

		annotation SummarizationSetBy = Automatic

	column DATE_ID
		dataType: int64
		formatString: 0
		lineageTag: 99885477-797e-4f77-9dd6-b7e130a0b780
		summarizeBy: none
		sourceColumn: DATE_ID

		annotation SummarizationSetBy = Automatic

	column INDICATOR_ID
		dataType: int64
		formatString: 0
		lineageTag: 420114f1-2034-43ef-ba83-18cebfd2da62
		summarizeBy: none
		sourceColumn: INDICATOR_ID

		annotation SummarizationSetBy = Automatic

	column VALUE
		dataType: double
		lineageTag: db94ea08-dff2-4617-9d39-7197d0f3a710
		summarizeBy: sum
		sourceColumn: VALUE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SOURCE
		dataType: string
		lineageTag: 941e209c-5d7f-49e8-aa50-e2fadbcd8234
		summarizeBy: none
		sourceColumn: SOURCE

		annotation SummarizationSetBy = Automatic

	column REFERENCE_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: ef2a6fa1-76f6-4316-bee6-259a6e5f421d
		summarizeBy: none
		sourceColumn: REFERENCE_DATE

		variation Variation
			isDefault
			relationship: 730ef826-4685-41af-a2a9-ed7f68454d6f
			defaultHierarchy: LocalDateTable_c38cb82b-859d-457e-b171-452b73fd75e0.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition fact_ratios = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\User\dev\BankingStudyDashboardPowerBI\data\processed\fact_ratios.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"ROW_ID", Int64.Type}, {"BANK_ID", Int64.Type}, {"COUNTRY_CODE", type text}, {"DATE_ID", Int64.Type}, {"INDICATOR_ID", Int64.Type}, {"VALUE", type text}, {"SOURCE", type text}, {"REFERENCE_DATE", type date}}),
				    #"Valeur remplacée" = Table.ReplaceValue(#"Type modifié",".",",",Replacer.ReplaceText,{"VALUE"}),
				    #"Type modifié1" = Table.TransformColumnTypes(#"Valeur remplacée",{{"VALUE", type number}})
				in
				    #"Type modifié1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

